import type { FriendLink, FriendsPageConfig } from "../types/friendsConfig";

// 可以在src/content/spec/friends.md中编写友链页面下方的自定义内容

// 友链页面配置
export const friendsPageConfig: FriendsPageConfig = {
	// 页面标题，如果留空则使用 i18n 中的翻译
	title: "",

	// 页面描述文本，如果留空则使用 i18n 中的翻译
	description: "",

	// 是否显示底部自定义内容（friends.mdx 中的内容）
	showCustomContent: true,

	// 是否显示评论区，需要先在commentConfig.ts启用评论系统
	showComment: true,

	// 是否开启随机排序配置，如果开启，就会忽略权重，构建时进行一次随机排序
	randomizeSort: false,
};

// 已加入的博客项目
export const friendsProjects: FriendLink[] = [
	{
		title: "博友圈",
		imgurl: "https://www.boyouquan.com/assets/images/sites/logo/logo-small.png",
		desc: "让我们跨越山海彼此相连，一起用文字打败时间！",
		siteurl: "https://www.boyouquan.com/home",
		screenshot: "/friends/screenshots/boyouquan.webp",
		tags: ["博客社区", "友链互推", "RSS"],
		weight: 40,
		enabled: true,
	},
	{
		title: "博客星球",
		imgurl: "https://www.blogplanet.cn/img/bkxq.png",
		desc: "每一个博客都是一个独立星球！",
		siteurl: "https://www.blogplanet.cn/",
		screenshot: "/friends/screenshots/blogplanet.webp",
		tags: ["博客社区", "博客收录", "博主交流"],
		weight: 30,
		enabled: true,
	},
	{
		title: "八零圈",
		imgurl: "https://80tz.cn/assets/images/sites/logo/logo-small.svg",
		desc: "自由、共享，给原创博客写作一个空间！",
		siteurl: "https://www.80tz.cn/home",
		screenshot: "/friends/screenshots/80tz.webp",
		tags: ["博客社区", "原创写作", "友链交流"],
		weight: 20,
		enabled: true,
	},
	{
		title: "BlogsClub",
		imgurl: "https://www.blogsclub.org/usr/themes/default/favicon.png",
		desc: "BlogsClub是一个互联网独立博客俱乐部。",
		siteurl: "https://www.blogsclub.org/",
		screenshot: "/friends/screenshots/blogsclub.webp",
		tags: ["博客社区", "博主交流", "博客收录"],
		weight: 10,
		enabled: true,
	},
	{
		title: "中文独立博客聚合列表",
		imgurl:
			"https://blogroll.online/wp-content/uploads/2026/07/android-chrome-512x512-1.png",
		desc: "又一个博客聚合站",
		siteurl: "https://blogroll.online/",
		screenshot: "/friends/screenshots/blogroll.webp",
		tags: ["博客聚合", "博客收录", "博客社区"],
		weight: 0,
		enabled: true,
	},
];

// 友链配置
export const friendsConfig: FriendLink[] = [
	{
		title: "jojo",
		imgurl: "https://rainzt.cn/zzty.png",
		desc: "物物而不物于物，念念而不念于念",
		siteurl: "https://rainzt.cn/",
		rss: "/rss.xml",
		screenshot: "https://rainzt.cn/index.png",
		tags: ["AI", "效率工具", "跨境电商"],
		weight: 100,
		enabled: true,
	},
	{
		title: "夏夜流萤",
		imgurl: "https://weavatar.com/avatar/d252655d40d6874417a720bad0a6c5f77f8f6a1fd2f882f8f338402dc37e4190?s=640",
		desc: "飞萤之火自无梦的长夜亮起，绽放在终竟的明天。",
		siteurl: "https://blog.cuteleaf.cn/",
		rss: "https://blog.cuteleaf.cn/rss.xml",
		screenshot: "/friends/screenshots/xia-ye-liu-ying.webp",
		tags: ["技术分享", "Firefly作者"],
		recommended: true,
		weight: 99.5,
		enabled: true,
	},
	{
		title: "AIOVTUE-雪",
		imgurl: "https://r2tc.20030327.xyz/file/博客/主题/1780655293662_avatar_me.jpg.PNG",
		desc: "雨滴会记录生命中的每一个瞬间",
		siteurl: "https://daily.yybb.us/",
		screenshot: "/friends/screenshots/aiovtue.webp",
		tags: ["博客主题", "开源", "教程"],
		recommended: true,
		weight: 99,
		enabled: true,
	},
	{
		title: "Homulilly",
		imgurl: "https://homulilly.com/images/avatar.jpg",
		desc: "圆环之外，仍有未尽之愿。",
		siteurl: "https://homulilly.com",
		rss: "https://homulilly.com/atom.xml",
		screenshot: "https://img.nep.me/blog/homulilly-home.webp",
		tags: ["Hexo", "博客主题", "开源"],
		recommended: true,
		weight: 98.5,
		enabled: true,
	},
	{
		title: "番茄主理人",
		imgurl: "https://q1.qlogo.cn/g?b=qq&nk=20447289&s=640",
		desc: "躬身入局，心为主理，行有尺度，自持本心.",
		siteurl: "https://blog.fqzlr.top/",
		screenshot: "/friends/screenshots/fqzlr.png",
		tags: ["个人博客", "技术分享", "建站记录"],
		recommended: true,
		recommendedTier: "degraded",
		weight: 98,
		enabled: true,
	},
	{
		title: "雨雪冰屋",
		imgurl: "https://iamyukino.cn/favicon.ico",
		desc: "一隅雨雪一炉窝，可能会融化持久堆？",
		siteurl: "https://iamyukino.cn/",
		rss: "https://iamyukino.cn/rss.xml",
		screenshot: "https://iamyukino.cn/siteshot.jpg",
		tags: ["个人博客", "技术分享", "资源分享"],
		weight: 97.5,
		enabled: true,
	},
	{
		title: "Asteri5m的小破站",
		imgurl: "https://asteri5m.icu/upload/20af907e-4769-4251-8e8c-0f0b52355380.png",
		desc: "别等时间不够的时候再后悔",
		siteurl: "https://asteri5m.icu/",
		screenshot: "/friends/screenshots/asteri5m.webp",
		tags: ["个人博客"],
		temporarilyUnavailable: true,
		weight: 85,
		enabled: true,
	},
	{
		title: "摸鱼の客栈",
		imgurl: "https://img.fwneko.com/ico/logo.gif",
		desc: "革命尚未成功，同志仍需努力",
		siteurl: "https://blog.fwneko.com/",
		screenshot: "/friends/screenshots/fwneko.webp",
		tags: ["个人博客"],
		weight: 80,
		enabled: true,
	},
	{
		title: "爱吃猫的鱼",
		imgurl: "https://image.talen.top/20251229184705_wgsva7g9.png",
		desc: "前景可待 未来可期",
		siteurl: "https://blog.talen.top/",
		screenshot: "/friends/screenshots/talen.webp",
		tags: ["建站", "自动化", "技术分享"],
		recommended: true,
		recommendedTier: "degraded",
		weight: 70,
		enabled: true,
	},
	{
		title: "时光潜流",
		imgurl: "https://www.dreamcenter.top/imgs/avatar.jpg",
		desc: "妹控的中二君！",
		siteurl: "http://www.dreamcenter.top/",
		rss: [
			"https://www.dreamcenter.top/BlogRss.xml",
			"https://www.dreamcenter.top/DailyRss.xml",
		],
		screenshot: "/friends/screenshots/dreamcenter.webp",
		tags: ["后端开发", "运维", "技术分享"],
		weight: 60,
		enabled: true,
	},
	{
		title: "灵的梦境",
		imgurl: "https://lemonadorable.github.io/favicon/favicon.gif",
		desc: "愿美梦成真",
		siteurl: "https://lemonadorable.github.io/",
		screenshot: "/friends/screenshots/lemonadorable.webp",
		tags: ["Astro", "技术笔记", "开源"],
		weight: 50,
		enabled: true,
	},
	{
		title: "Xgrblog",
		imgurl: "https://xgrblog.cn/avatar.jpg",
		desc: "学无止境",
		siteurl: "https://xgrblog.cn/",
		screenshot: "/friends/screenshots/xgrblog.webp",
		tags: ["个人博客"],
		weight: 40,
		enabled: true,
	},
	{
		title: "Detached",
		imgurl: "https://detached.online/icon-512.png",
		desc: "独立开发者的技术、工具与生活博客",
		siteurl: "https://detached.online/",
		screenshot: "/friends/screenshots/detached.webp",
		tags: ["独立开发", "技术工具", "生活记录"],
		recommended: true,
		weight: 98.25,
		enabled: true,
	},
	{
		title: "茗辰原",
		imgurl: "https://mingcy.cn/image/mcy.png",
		desc: "茶香四溢，编程世界",
		siteurl: "https://mingcy.cn/",
		screenshot: "/friends/screenshots/mingcy.webp",
		tags: ["编程", "个人博客"],
		weight: -10,
		enabled: true,
	},
	{
		title: "小曦的园子",
		imgurl: "https://img.xiaoxi.ac.cn/logo.png",
		desc: "打理好自己的小园子",
		siteurl: "https://xiaoxi.ac.cn/",
		screenshot: "/friends/screenshots/xiaoxi.webp",
		tags: ["个人博客", "生活记录"],
		recommended: true,
		recommendedTier: "degraded",
		weight: 97.6,
		enabled: true,
	},
	{
		title: "Petrichor's Blog",
		imgurl: "https://blog.telyra.top/avatar.webp",
		desc: "在技术与日常之间，随心记录一些独特的想法。",
		siteurl: "https://blog.telyra.top/",
		screenshot: "/friends/screenshots/telyra.webp",
		tags: ["个人博客", "技术随笔", "生活记录"],
		recommended: true,
		recommendedTier: "degraded",
		weight: -30,
		enabled: true,
	},
	{
		title: "Ming Blog",
		imgurl: "https://mingblog.site/icons/icon-512.png",
		desc: "记录日常生活、城市影像、旅行与观察，以及认真看过、读过和听过的作品。",
		siteurl: "https://mingblog.site/",
		screenshot: "/friends/screenshots/mingblog.webp",
		tags: ["个人博客", "生活记录", "旅行观察"],
		recommended: true,
		recommendedTier: "degraded",
		weight: -40,
		enabled: true,
	},
	{
		title: "Ditto",
		imgurl: "https://gcore.jsdelivr.net/gh/Keduoli03/My_img@img/avatar.jpg",
		desc: "请为一切不真实之物骄傲，因为我们高于这个世界！",
		siteurl: "https://blog.blueke.top/",
		screenshot: "/friends/screenshots/ditto.webp",
		tags: ["Astro", "AI", "技术分享"],
		recommended: true,
		recommendedTier: "degraded",
		weight: -50,
		enabled: true,
	},
	{
		title: "sssr7844的博客",
		imgurl:
			"https://sssr7844.cc.cd/wp-content/uploads/2026/07/1785027509-霞塔_original-scaled-e1785157015117.jpg",
		desc: "Just for fun",
		siteurl: "https://sssr7844.cc.cd/",
		screenshot: "/friends/screenshots/sssr7844.webp",
		tags: ["WordPress", "ACG", "技术分享"],
		weight: -60,
		enabled: true,
	},
	{
		title: "拾柒",
		imgurl: "https://www.s17.cn/logo.png",
		desc: "活在当下 随遇而安 早睡早起 每天开心👐🏼",
		siteurl: "https://www.s17.cn/",
		screenshot: "/friends/screenshots/s17.webp",
		tags: ["Typecho", "生活随笔", "技术折腾"],
		weight: -70,
		enabled: true,
	},
	{
		title: "桃之夭夭",
		imgurl: "https://taozhiyy.top/cos/1.png",
		desc: "桃之夭夭的小屋",
		siteurl: "https://taozhiyy.top/",
		screenshot: "/friends/screenshots/taozhiyy.webp",
		tags: ["React", "AI", "建站记录"],
		recommended: true,
		recommendedTier: "degraded",
		weight: -80,
		enabled: true,
	},
	{
		title: "九仞之行",
		imgurl:
			"https://gravatar.loli.net/avatar/e4798a16feefbbe2d4b74d6fd4b8a3184133ae13b68305b223a9453fc11527e4?s=256&r=g&d=404",
		desc: "严于律己，宽以待人，深自警省，讷言敏行",
		siteurl: "https://styunlen.cn/",
		screenshot: "/friends/screenshots/styunlen.webp",
		tags: ["WordPress", "编程", "Linux"],
		weight: -90,
		enabled: true,
	},
	{
		title: "林子浩的日记",
		imgurl: "https://lzh1.cn/favicon.ico",
		desc: "一个努力写日记的博客站长。",
		siteurl: "https://lzh1.cn/",
		screenshot: "/friends/screenshots/linzihao.webp",
		tags: ["Typecho", "生活记录", "技术分享"],
		weight: -100,
		enabled: true,
	},
	{
		title: "王一君Mew",
		imgurl: "https://wyjmew.cn/app.png",
		desc: "你奔向我的每一步，都是我心动的理由",
		siteurl: "https://wyjmew.cn/",
		screenshot: "/friends/screenshots/wyjmew.webp",
		tags: ["生活记录", "技术分享", "Docker"],
		weight: -110,
		enabled: true,
	},
	{
		title: "路明笔记",
		imgurl: "https://image.luming.cool/i/2026/05/10/6a001b4129893.png",
		desc: "一名高中生的技术和生活博客。",
		siteurl: "https://www.luming.cool/",
		rss: "https://www.luming.cool/rss.xml",
		screenshot: "/friends/screenshots/luming.webp",
		tags: ["Astro", "生活记录", "技术分享"],
		weight: -120,
		enabled: true,
	},
	{
		title: "林间随笔",
		imgurl: "https://linyu.live/logo.png",
		desc: "以此林间笔墨纸，写尽世间温柔事",
		siteurl: "https://linyu.live/",
		screenshot: "/friends/screenshots/linyu.webp",
		tags: ["Typecho", "生活随笔", "旅行观察"],
		weight: -130,
		enabled: true,
	},
	{
		title: "陈义程博客",
		imgurl: "https://chenyicheng.cn/assets/images/avatar1.png",
		desc: "独行于比特荒野 不是造物主便是幽灵.",
		siteurl: "https://www.chenyicheng.cn/",
		screenshot: "/friends/screenshots/chenyicheng.webp",
		tags: ["Astro", "技术分享", "生活记录"],
		weight: -140,
		enabled: true,
	},
	{
		title: "Sunrise's blog",
		imgurl: "https://wowtang.top/images/avatar.png",
		desc: "心境自成天地，地狱可化作桃源，天堂也能沦为苦海。",
		siteurl: "https://wowtang.top/",
		screenshot: "/friends/screenshots/sunrise.webp",
		tags: ["Gridea", "技术分享", "生活随笔"],
		weight: -150,
		enabled: true,
	},
	{
		title: "日和",
		imgurl: "https://i0.hdslb.com/bfs/face/a09cb25595f69324ed7da361391de337dbe47601.jpg",
		desc: "想把一些代码笔记、阅读碎片和日常里的小幸福慢慢留下来，以及分享一些有趣的东西",
		siteurl: "https://codevfun.work/",
		rss: "https://codevfun.work/feed.xml",
		screenshot: "https://codevfun.work/api/img/1787289449376-r1f0io.webp?w=1200",
		tags: ["个人博客", "代码笔记", "阅读记录", "生活记录"],
		weight: -160,
		enabled: true,
	},
	{
		title: "星空驿站",
		imgurl: "https://baiyangmu.xyz/static/favicon-96x96.png",
		desc: "一座漂浮在深空中的小小驿站",
		siteurl: "https://baiyangmu.xyz/",
		screenshot: "https://baiyangmu.xyz/static/home-screenshot.png",
		tags: ["个人博客", "技术教程", "科幻主题"],
		weight: -170,
		enabled: true,
	},
	{
		title: "Xe_iu的杂物间",
		imgurl: "https://blog.xeiu.top/logo-img/logo.jpg",
		desc: "改变不了这个世界，那就默默活在其中。",
		siteurl: "https://blog.xeiu.top/",
		screenshot: "/friends/screenshots/xeiu.webp",
		tags: ["个人博客", "生活随笔", "生活记录"],
		weight: -180,
		enabled: true,
	},
	{
		title: "没吃饱的天镜镜",
		imgurl: "https://blogr2.8765777.xyz/assets/my/7590A261E0E39A642ABF4873E89EAFF9.jpg",
		desc: "诺贝尔奖关注者，文学奖读者",
		siteurl: "https://blog.8765777.xyz/",
		rss: "https://blog.8765777.xyz/rss.xml",
		screenshot: "https://blogr2.8765777.xyz/friends/blog-screenshot.png",
		tags: ["个人博客", "阅读记录", "文学随笔"],
		weight: -190,
		enabled: true,
	},
	{
		title: "I'm WhiteBear",
		imgurl: "https://whitebear.im/usr/uploads/2024/11/568223243.png",
		desc: "记录代码与日常生活的个人自留地。",
		siteurl: "https://whitebear.im/",
		rss: "https://whitebear.im/feed/",
		screenshot: "/friends/screenshots/whitebear.webp",
		tags: ["Typecho", "生活记录", "技术分享"],
		weight: -200,
		enabled: true,
	},
	{
		title: "0c0 的小窝",
		imgurl: "https://blog.0c0.ren/favicon.ico",
		desc: "0c0 的奇奇怪怪想法堆积处",
		siteurl: "https://blog.0c0.ren/",
		rss: "https://blog.0c0.ren/feed",
		screenshot: "/friends/screenshots/0c0.webp",
		tags: ["Typecho", "技术分享", "生活随笔"],
		weight: -210,
		enabled: true,
	},
	{
		title: "黄鼠狼的树洞",
		imgurl: "https://files.seeusercontent.com/2026/06/26/Fo0x/LOGO.webp",
		desc: "小黄的博客，记录生活中的美好",
		siteurl: "https://blog.weasel6.cn/",
		rss: "https://blog.weasel6.cn/rss.xml",
		screenshot: "/friends/screenshots/weasel6.webp",
		tags: ["个人博客", "生活记录", "ACG"],
		weight: -220,
		enabled: true,
	},
	{
		title: "Evilrabbit Blog",
		imgurl: "https://blog.yujiay.wang/images/site/BlogHsvg.png",
		desc: "爱 Coding 爱生活",
		siteurl: "https://blog.yujiay.wang/",
		screenshot: "https://blog.yujiay.wang/images/link/2025/EvilrabbitBlog.jpg",
		tags: ["技术分享", "C++", "AI"],
		weight: -230,
		enabled: true,
	},
	{
		title: "楠枝小笺",
		imgurl: "https://www.nanzhiy.cn/upload/avatar.jpg",
		desc: "安安静静地存在，就已经很好啦。",
		siteurl: "https://www.nanzhiy.cn/",
		rss: "https://www.nanzhiy.cn/rss.xml",
		screenshot: "/friends/screenshots/nanzhiy.webp",
		tags: ["个人博客", "技术分享", "生活记录"],
		weight: -240,
		enabled: true,
	},
	{
		title: "睿朗的小窝",
		imgurl: "https://iamcrl.cn/avatar.jpg",
		desc: "永远相信美好的事情即将发生",
		siteurl: "https://notes.iamcrl.cn/",
		rss: "https://notes.iamcrl.cn/rss.xml",
		screenshot: "https://iamcrl.cn/files/notes.png",
		tags: ["个人博客", "技术分享", "生活记录"],
		weight: -250,
		enabled: true,
	},
	{
		title: "Moyor的炼药小锅",
		imgurl: "https://moyor.cc/images/logo.svg",
		desc: "把代码、美术与创意熬成游戏的炼药锅。",
		siteurl: "https://moyor.cc/",
		screenshot: "https://moyor.cc/images/og.webp",
		tags: ["独立开发", "游戏开发", "技术分享"],
		weight: -260,
		enabled: true,
	},
	{
		title: "SilverCode_Nexus",
		imgurl: "https://cdn.replow.org/replow-org/images/tx.ico",
		desc: "Replow的小站",
		siteurl: "https://www.replow.org/",
		screenshot: "/friends/screenshots/silvercode-nexus.webp",
		tags: ["个人博客", "ACG", "游戏分享"],
		weight: -270,
		enabled: true,
	},
	{
		title: "清吾",
		imgurl: "https://www.qingwu.ink/images/avatar.jpg",
		desc: "写技术、记生活，一个温馨二次元的小屋。",
		siteurl: "https://www.qingwu.ink/",
		rss: "https://www.qingwu.ink/rss.xml",
		screenshot: "https://www.qingwu.ink/images/home.png",
		tags: ["个人博客", "技术分享", "生活记录"],
		weight: -280,
		enabled: true,
	},
	{
		title: "Wangxinyang",
		imgurl: "https://wangxinyang.top/avatar.png",
		desc: "个人博客 / 学习交流 / 生活日常",
		siteurl: "https://wangxinyang.top/",
		rss: "https://wangxinyang.top/rss.xml",
		screenshot: "https://wangxinyang.top/upload/zhuye.png",
		tags: ["个人博客", "学习交流", "生活日常"],
		weight: -290,
		enabled: true,
	},
	{
		title: "小生云",
		imgurl: "https://file.zsso.cn/assets/ZSSO11787933525826169.png",
		desc: "小生云|支付|加速",
		siteurl: "https://www.zsso.cn/",
		screenshot: "/friends/screenshots/xiaoshengyun.webp",
		tags: ["支付", "加速服务"],
		weight: -300,
		enabled: true,
	},
	{
		title: "第四世界",
		imgurl: "https://onewumi.com/wp-content/uploads/2025/10/cropped-cropped-cropped-cropped-4world-LOGO-scaled-1-192x192.png",
		desc: "记录生活、分享思考、创造美。",
		siteurl: "https://onewumi.com/",
		rss: "https://onewumi.com/feed/",
		screenshot: "https://onewumi.com/wp-content/uploads/2025/09/1-1024x576.png",
		tags: ["个人博客", "生活记录", "技术分享"],
		weight: -310,
		enabled: true,
	},
	{
		title: "折腾进行中",
		imgurl: "https://www.9ll.uk/gallery/blog/avatar.avif",
		desc: "记录一些生活，爱好技术和相关的东西。",
		siteurl: "https://www.9ll.uk/",
		rss: "https://www.9ll.uk/rss.xml",
		screenshot: "https://www.9ll.uk/gallery/blog/homepage.png",
		tags: ["个人博客", "生活记录", "技术分享"],
		weight: -320,
		enabled: true,
	},
	{
		title: "UpXuu’s blog",
		imgurl: "https://upxuu.com/images/me.jpg",
		desc: "逐光而上",
		siteurl: "https://upxuu.com",
		rss: "https://upxuu.com/rss.xml",
		screenshot: "/friends/screenshots/upxuu.webp",
		tags: ["个人博客", "技术分享", "生活记录"],
		weight: -330,
		enabled: true,
	},
	{
		title: "星宇安全实验室",
		imgurl:
			"https://bk.zhaozhiqiang.pw/wp-content/uploads/2026/07/1784847314130_148x148.png",
		desc: "星宇安全实验室，专注网络安全技术分享，记录团队实战经历、安全研究与编程成长笔记，致力于分享网安学习干货。",
		siteurl: "https://bk.zhaozhiqiang.pw",
		rss: "https://bk.zhaozhiqiang.pw/feed",
		screenshot: "https://bk.zhaozhiqiang.pw/wp-content/uploads/2026/09/2026-09-09-140947.png",
		tags: ["网络安全", "技术分享", "编程成长"],
		weight: -340,
		enabled: true,
	},
	{
		title: "铭心の博客",
		imgurl: "https://www.mxin.me/favicon.ico",
		desc: "铭心的个人小窝(๑•ᴗ•๑)",
		siteurl: "https://www.mxin.me",
		screenshot: "/friends/screenshots/mxin.webp",
		tags: ["个人博客"],
		weight: -350,
		enabled: true,
	},
	{
		title: "冷月笙寒的小窝",
		imgurl: "https://lygalaxy.cn/uploads/20260128_200240_6979fae094c7b.jpg",
		desc: "发现巷子里的那颗星星(技术与生活分享)",
		siteurl: "https://lygalaxy.cn/",
		rss: "https://lygalaxy.cn/license/rss.php",
		screenshot: "/friends/screenshots/lygalaxy.webp",
		tags: ["个人博客", "技术分享", "生活记录"],
		weight: -360,
		enabled: true,
	},
];

// 获取启用的友链并进行排序
export const getEnabledFriends = (): FriendLink[] => {
	const friends = friendsConfig.filter((friend) => friend.enabled);

	if (friendsPageConfig.randomizeSort) {
		return friends.sort(() => Math.random() - 0.5);
	}

	return friends.sort((a, b) => b.weight - a.weight);
};
