// 每日英语精选词库：每天按日期轮换一词，无需外部 API
export interface EnglishWord {
	word: string;
	phonetic: string;
	pos: string;
	meaning: string;
	example: string;
	exampleZh: string;
}

export const ENGLISH_WORDS: EnglishWord[] = [
	{
		word: "serendipity",
		phonetic: "/ˌserənˈdɪpəti/",
		pos: "n.",
		meaning: "意外发现美好事物的运气",
		example: "Finding this little cafe was pure serendipity.",
		exampleZh: "发现这家小咖啡馆纯属偶然的惊喜。",
	},
	{
		word: "blossom",
		phonetic: "/ˈblɒsəm/",
		pos: "n./v.",
		meaning: "花；开花；成长",
		example: "She has blossomed into a confident writer.",
		exampleZh: "她已成长为一名自信的作家。",
	},
	{
		word: "wander",
		phonetic: "/ˈwɒndə/",
		pos: "v.",
		meaning: "漫步，闲逛",
		example: "We wandered around the old town all afternoon.",
		exampleZh: "我们整个下午都在老城里闲逛。",
	},
	{
		word: "cozy",
		phonetic: "/ˈkəʊzi/",
		pos: "adj.",
		meaning: "温暖舒适的",
		example: "The room feels cozy on rainy days.",
		exampleZh: "雨天里这房间显得格外温馨。",
	},
	{
		word: "petrichor",
		phonetic: "/ˈpetrɪkɔː/",
		pos: "n.",
		meaning: "雨后泥土的清香",
		example: "The petrichor after the storm was refreshing.",
		exampleZh: "暴雨后的泥土清香令人心旷神怡。",
	},
	{
		word: "serene",
		phonetic: "/səˈriːn/",
		pos: "adj.",
		meaning: "宁静的，安详的",
		example: "The lake was serene at dawn.",
		exampleZh: "黎明时分，湖面宁静安详。",
	},
	{
		word: "dawn",
		phonetic: "/dɔːn/",
		pos: "n.",
		meaning: "黎明，开端",
		example: "Hope is a good breakfast at dawn.",
		exampleZh: "黎明时的希望是一顿好早餐。",
	},
	{
		word: "melody",
		phonetic: "/ˈmelədi/",
		pos: "n.",
		meaning: "旋律，曲调",
		example: "She hummed a melody from her childhood.",
		exampleZh: "她哼着童年的一首旋律。",
	},
	{
		word: "nostalgia",
		phonetic: "/nɒˈstældʒə/",
		pos: "n.",
		meaning: "怀旧，乡愁",
		example: "The old song filled him with nostalgia.",
		exampleZh: "那首老歌让他满心怀念。",
	},
	{
		word: "gratitude",
		phonetic: "/ˈɡrætɪtjuːd/",
		pos: "n.",
		meaning: "感激之情",
		example: "I would like to express my gratitude to you.",
		exampleZh: "我想向你表达我的感激。",
	},
	{
		word: "shimmer",
		phonetic: "/ˈʃɪmə/",
		pos: "v.",
		meaning: "闪烁，微微发亮",
		example: "The sea shimmered under the moonlight.",
		exampleZh: "海面在月光下微微闪烁。",
	},
	{
		word: "whisper",
		phonetic: "/ˈwɪspə/",
		pos: "v.",
		meaning: "低语，轻声说",
		example: "The wind whispered through the trees.",
		exampleZh: "风在林间低语。",
	},
	{
		word: "drizzle",
		phonetic: "/ˈdrɪzl/",
		pos: "n./v.",
		meaning: "毛毛雨；下蒙蒙细雨",
		example: "A light drizzle began to fall.",
		exampleZh: "开始下起了蒙蒙细雨。",
	},
	{
		word: "twilight",
		phonetic: "/ˈtwaɪlaɪt/",
		pos: "n.",
		meaning: "黄昏，暮光",
		example: "They took a walk in the twilight.",
		exampleZh: "他们在暮色中散步。",
	},
	{
		word: "solitude",
		phonetic: "/ˈsɒlɪtjuːd/",
		pos: "n.",
		meaning: "独处，宁静",
		example: "He enjoys the solitude of early mornings.",
		exampleZh: "他享受清晨的独处时光。",
	},
	{
		word: "thriving",
		phonetic: "/ˈθraɪvɪŋ/",
		pos: "adj.",
		meaning: "欣欣向荣的",
		example: "The little shop is thriving this year.",
		exampleZh: "这家小店今年生意兴隆。",
	},
	{
		word: "gentle",
		phonetic: "/ˈdʒentl/",
		pos: "adj.",
		meaning: "温柔的，温和的",
		example: "A gentle breeze touched her face.",
		exampleZh: "微风轻拂她的脸庞。",
	},
	{
		word: "glimmer",
		phonetic: "/ˈɡlɪmə/",
		pos: "n.",
		meaning: "微光，一丝（希望）",
		example: "There is a glimmer of hope in his words.",
		exampleZh: "他的话里透着一丝希望。",
	},
	{
		word: "cascade",
		phonetic: "/kæˈskeɪd/",
		pos: "n./v.",
		meaning: "瀑布般落下；层叠",
		example: "Her hair cascaded over her shoulders.",
		exampleZh: "她的长发如瀑布般垂在肩上。",
	},
	{
		word: "breeze",
		phonetic: "/briːz/",
		pos: "n.",
		meaning: "微风；轻而易举的事",
		example: "The exam was a breeze for her.",
		exampleZh: "这场考试对她来说轻而易举。",
	},
	{
		word: "radiant",
		phonetic: "/ˈreɪdiənt/",
		pos: "adj.",
		meaning: "容光焕发的，光芒四射的",
		example: "She looked radiant on her wedding day.",
		exampleZh: "婚礼那天她容光焕发。",
	},
	{
		word: "tranquil",
		phonetic: "/ˈtræŋkwɪl/",
		pos: "adj.",
		meaning: "安静的，平和的",
		example: "The village is tranquil in winter.",
		exampleZh: "冬天的村庄宁静祥和。",
	},
	{
		word: "delight",
		phonetic: "/dɪˈlaɪt/",
		pos: "n./v.",
		meaning: "高兴；使愉悦",
		example: "The kids screamed with delight.",
		exampleZh: "孩子们高兴得尖叫起来。",
	},
	{
		word: "cherish",
		phonetic: "/ˈtʃerɪʃ/",
		pos: "v.",
		meaning: "珍惜，珍爱",
		example: "I cherish the memories of that summer.",
		exampleZh: "我珍惜那个夏天的回忆。",
	},
	{
		word: "ember",
		phonetic: "/ˈembə/",
		pos: "n.",
		meaning: "余烬，余温",
		example: "The embers of the fire kept us warm.",
		exampleZh: "炉火的余烬温暖着我们。",
	},
	{
		word: "soothe",
		phonetic: "/suːð/",
		pos: "v.",
		meaning: "安抚，缓和",
		example: "The soft music soothed the baby.",
		exampleZh: "轻柔的音乐安抚了宝宝。",
	},
	{
		word: "gleam",
		phonetic: "/ɡliːm/",
		pos: "v.",
		meaning: "发光，闪亮",
		example: "The morning sun gleamed on the wet grass.",
		exampleZh: "朝阳在湿润的草地上闪闪发光。",
	},
	{
		word: "flourish",
		phonetic: "/ˈflʌrɪʃ/",
		pos: "v.",
		meaning: "繁荣，茂盛；挥舞",
		example: "Wildflowers flourish along the path.",
		exampleZh: "野花在小路旁繁盛生长。",
	},
	{
		word: "hush",
		phonetic: "/hʌʃ/",
		pos: "n./v.",
		meaning: "寂静；使安静",
		example: "A hush fell over the room.",
		exampleZh: "房间里一片寂静。",
	},
	{
		word: "luminous",
		phonetic: "/ˈluːmɪnəs/",
		pos: "adj.",
		meaning: "发光的，明亮的",
		example: "Stars were luminous in the dark sky.",
		exampleZh: "星星在夜空中明亮闪烁。",
	},
	{
		word: "mellow",
		phonetic: "/ˈmeləʊ/",
		pos: "adj.",
		meaning: "柔和的，成熟的",
		example: "Autumn light is soft and mellow.",
		exampleZh: "秋日的光线柔和温润。",
	},
	{
		word: "savor",
		phonetic: "/ˈseɪvə/",
		pos: "v.",
		meaning: "细细品味",
		example: "She savored every bite of the cake.",
		exampleZh: "她细细品味着蛋糕的每一口。",
	},
	{
		word: "untold",
		phonetic: "/ʌnˈtəʊld/",
		pos: "adj.",
		meaning: "数不清的；未曾讲述的",
		example: "The old house holds untold stories.",
		exampleZh: "老房子里藏着无数未曾讲述的故事。",
	},
	{
		word: "velvet",
		phonetic: "/ˈvelvɪt/",
		pos: "n./adj.",
		meaning: "天鹅绒；柔软光滑的",
		example: "The night sky felt like velvet.",
		exampleZh: "夜空如天鹅绒般柔软。",
	},
	{
		word: "wholesome",
		phonetic: "/ˈhəʊlsəm/",
		pos: "adj.",
		meaning: "有益身心健康的",
		example: "They enjoyed a wholesome breakfast together.",
		exampleZh: "他们一起享用了健康的早餐。",
	},
	{
		word: "yearn",
		phonetic: "/jɜːn/",
		pos: "v.",
		meaning: "渴望，向往",
		example: "He yearned for the sea during winter.",
		exampleZh: "冬天里他格外向往大海。",
	},
	{
		word: "amiable",
		phonetic: "/ˈeɪmiəbl/",
		pos: "adj.",
		meaning: "和蔼可亲的",
		example: "Our new neighbor is amiable and kind.",
		exampleZh: "我们的新邻居和蔼友善。",
	},
	{
		word: "bliss",
		phonetic: "/blɪs/",
		pos: "n.",
		meaning: "极大的幸福",
		example: "Reading by the fire is pure bliss.",
		exampleZh: "炉边读书是纯粹的幸福。",
	},
	{
		word: "cradle",
		phonetic: "/ˈkreɪdl/",
		pos: "n.",
		meaning: "摇篮；发源地",
		example: "The valley is the cradle of the civilization.",
		exampleZh: "这片山谷是文明的摇篮。",
	},
	{
		word: "dazzle",
		phonetic: "/ˈdæzl/",
		pos: "v.",
		meaning: "使目眩，使赞叹",
		example: "The sunrise dazzled all of us.",
		exampleZh: "日出让我们所有人都目眩神迷。",
	},
	{
		word: "evoke",
		phonetic: "/ɪˈvəʊk/",
		pos: "v.",
		meaning: "唤起，引起",
		example: "The scent evokes memories of home.",
		exampleZh: "这气味唤起了家的记忆。",
	},
	{
		word: "fleck",
		phonetic: "/flek/",
		pos: "n.",
		meaning: "斑点，微粒",
		example: "Golden flecks danced on the water.",
		exampleZh: "金色光斑在水面上跳动。",
	},
	{
		word: "glow",
		phonetic: "/ɡləʊ/",
		pos: "v.",
		meaning: "发光，发热",
		example: "Her face glowed with happiness.",
		exampleZh: "她的脸上洋溢着幸福的光彩。",
	},
	{
		word: "haven",
		phonetic: "/ˈheɪvn/",
		pos: "n.",
		meaning: "避风港，安全处",
		example: "The library is my quiet haven.",
		exampleZh: "图书馆是我安静的避风港。",
	},
	{
		word: "iridescent",
		phonetic: "/ˌɪrɪˈdesnt/",
		pos: "adj.",
		meaning: "彩虹色的，异彩纷呈的",
		example: "Soap bubbles are iridescent in sunlight.",
		exampleZh: "肥皂泡在阳光下泛着七彩光泽。",
	},
	{
		word: "kismet",
		phonetic: "/ˈkɪzmet/",
		pos: "n.",
		meaning: "命运，天意",
		example: "Meeting her felt like kismet.",
		exampleZh: "遇见她仿佛是命中注定。",
	},
	{
		word: "lush",
		phonetic: "/lʌʃ/",
		pos: "adj.",
		meaning: "茂盛的，青葱的",
		example: "The valley is lush after spring rains.",
		exampleZh: "春雨过后山谷青葱繁茂。",
	},
	{
		word: "momentum",
		phonetic: "/məˈmentəm/",
		pos: "n.",
		meaning: "势头，动力",
		example: "Keep the momentum going, little by little.",
		exampleZh: "一点一点，保持势头。",
	},
	{
		word: "nuance",
		phonetic: "/ˈnjuːɑːns/",
		pos: "n.",
		meaning: "细微差别",
		example: "A good writer understands every nuance of a word.",
		exampleZh: "好的作家理解词语间的细微差别。",
	},
	{
		word: "opulent",
		phonetic: "/ˈɒpjələnt/",
		pos: "adj.",
		meaning: "华丽的，奢华的",
		example: "The palace has opulent halls and gardens.",
		exampleZh: "宫殿里有奢华的大厅和花园。",
	},
	{
		word: "pause",
		phonetic: "/pɔːz/",
		pos: "n./v.",
		meaning: "停顿，暂停",
		example: "Take a pause and breathe deeply.",
		exampleZh: "停一停，深呼吸。",
	},
	{
		word: "quaint",
		phonetic: "/kweɪnt/",
		pos: "adj.",
		meaning: "古雅别致的",
		example: "We stayed in a quaint little village.",
		exampleZh: "我们住在一个古朴别致的小村庄。",
	},
	{
		word: "relish",
		phonetic: "/ˈrelɪʃ/",
		pos: "v.",
		meaning: "享受，回味",
		example: "He relished the quiet Sunday morning.",
		exampleZh: "他享受着周日宁静的清晨。",
	},
	{
		word: "spellbound",
		phonetic: "/ˈspelbaʊnd/",
		pos: "adj.",
		meaning: "入迷的，出神的",
		example: "The children listened, spellbound.",
		exampleZh: "孩子们听得入了迷。",
	},
	{
		word: "tryst",
		phonetic: "/trɪst/",
		pos: "n.",
		meaning: "约会，幽会",
		example: "Spring keeps its tryst with flowers every year.",
		exampleZh: "春天每年都如约与花朵相见。",
	},
	{
		word: "utopia",
		phonetic: "/juːˈtəʊpiə/",
		pos: "n.",
		meaning: "乌托邦，理想之地",
		example: "Every reader has a private utopia.",
		exampleZh: "每个读者心中都有一座理想国。",
	},
	{
		word: "vivid",
		phonetic: "/ˈvɪvɪd/",
		pos: "adj.",
		meaning: "生动的，鲜明的",
		example: "The dream left vivid images in her mind.",
		exampleZh: "梦境在她脑海中留下鲜明的画面。",
	},
	{
		word: "wistful",
		phonetic: "/ˈwɪstfl/",
		pos: "adj.",
		meaning: "怅然若失的，留恋的",
		example: "She gave the old photo a wistful smile.",
		exampleZh: "她望着旧照片，怅然微笑。",
	},
	{
		word: "zenith",
		phonetic: "/ˈzenɪθ/",
		pos: "n.",
		meaning: "顶点，巅峰",
		example: "The city reached its zenith in the 1920s.",
		exampleZh: "这座城市在二十世纪二十年代达到巅峰。",
	},
	{
		word: "aurora",
		phonetic: "/ɔːˈrɔːrə/",
		pos: "n.",
		meaning: "极光，晨曦",
		example: "We watched the aurora dance all night.",
		exampleZh: "我们整夜看着极光舞动。",
	},
];

/**
 * 获取某天的单词（按 Unix 天数循环，同一天固定同一词）
 * offset 为负数表示往前的天数（用于历史回顾）
 */
export function getWordOfDay(now: Date = new Date(), offset = 0): EnglishWord {
	const dayIndex = Math.floor(now.getTime() / (24 * 60 * 60 * 1000)) + offset;
	const index =
		((dayIndex % ENGLISH_WORDS.length) + ENGLISH_WORDS.length) %
		ENGLISH_WORDS.length;
	return ENGLISH_WORDS[index];
}
